sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shakilajayarathna/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run shakilajayarathna/react-test npm test -- --coverage
  #- docker run -e CI=true stephengrider/react-test npm test

after_success:
  - docker build -t shakilajayarathna/multi-client ./client4
  - docker build -t shakilajayarathna/multi-nginx ./nginx
  - docker build -t shakilajayarathna/multi-server ./server
  - docker build -t shakilajayarathna/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push shakilajayarathna/multi-client
  - docker push shakilajayarathna/multi-nginx
  - docker push shakilajayarathna/multi-server
  - docker push shakilajayarathna/multi-worker
